---
# TODO: handle more than just Centos 7
# NOTE: at present, Centos 7 yum install is incompatible with everything else:
# https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPLinuxRPMInstall
- name: add shibboeth repo - CentOS 7
  yum_repository:
    name: shibboleth
    description: "Shibboleth (CentOS_7)"
    mirrorlist: "{{ shib_repo_mirrorlist }}"
    gpgkey:   "{{ shib_repo_gpgkey }}"
    gpgcheck: yes
    enabled: yes
  when: ansible_os_family == 'RedHat'

- name: install shibboleth-sp
  yum:
    name: "{{ shib_package }}"
    enablerepo: shibboleth
    state: present
